### Imports
We begin by importing all the necessary libraries for our preprocessing tasks.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

print("Libraries imported successfully!")

Libraries imported successfully!

### Create Sample Dataset

In [ ]:
raw_data = {
    'Age': [22, 25, 47, 35, np.nan, 28, 55, 60, 24, 31],
    'Salary': [45000, 52000, 110000, 75000, 62000, 58000, 125000, 250000, np.nan, 300000],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', np.nan, 'Male', 'Female', 'Female'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', np.nan],
    'Date': ['2023-01-15', '2023-01-16', '2023-02-20', '2023-03-12', '2023-04-05', '2023-05-18', '2023-06-22', '2023-07-01', '2023-08-11', '2023-09-05'],
    'Purchase_Amount': [120.50, 85.00, 450.25, 300.00, 50.00, 150.75, 520.00, 1200.00, 95.00, 210.00],
    'Experience': [1, 2, 15, 8, 4, 5, 20, 25, 2, 6],
    'Rating': [3.5, 4.0, 4.5, 4.2, 3.8, 3.9, 4.8, 5.0, 3.7, 4.1]
}

df_original = pd.DataFrame(raw_data)
df = df_original.copy()

print("Original Dataset Summary:")
display(df.info())
display(df.head(10))

Original Dataset Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              9 non-null      float64
 1   Salary           9 non-null      float64
 2   Gender           9 non-null      object
 3   City             9 non-null      object
 4   Date             10 non-null     object
 5   Purchase_Amount  10 non-null     float64
 6   Experience       10 non-null     int64
 7   Rating           10 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 772.0+ bytes

None

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.0,45000.0,Male,New York,2023-01-15,120.50,1,3.5
1,25.0,52000.0,Female,Los Angeles,2023-01-16,85.00,2,4.0
2,47.0,110000.0,Female,Chicago,2023-02-20,450.25,15,4.5
3,35.0,75000.0,Male,New York,2023-03-12,300.00,8,4.2
4,NaN,62000.0,Female,Chicago,2023-04-05,50.00,4,3.8
5,28.0,58000.0,Male,Los Angeles,2023-05-18,150.75,5,3.9
6,55.0,125000.0,NaN,New York,2023-06-22,520.00,20,4.8
7,60.0,250000.0,Male,Chicago,2023-07-01,1200.00,25,5.0
8,24.0,NaN,Female,Los Angeles,2023-08-11,95.00,2,3.7
9,31.0,300000.0,Female,NaN,2023-09-05,210.00,6,4.1

### Problem 1: Handling Missing Values
We will fill numerical columns with their mean and categorical columns with their mode.

In [ ]:
for col in ['Age', 'Salary']:
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)

for col in ['Gender', 'City']:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

print("Missing values per column after imputation:")
print(df.isnull().sum())
display(df.head(10))

Missing values per column after imputation:
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.000000,45000.000000,Male,New York,2023-01-15,120.50,1,3.5
1,25.000000,52000.000000,Female,Los Angeles,2023-01-16,85.00,2,4.0
2,47.000000,110000.000000,Female,Chicago,2023-02-20,450.25,15,4.5
3,35.000000,75000.000000,Male,New York,2023-03-12,300.00,8,4.2
4,36.333333,62000.000000,Female,Chicago,2023-04-05,50.00,4,3.8
5,28.000000,58000.000000,Male,Los Angeles,2023-05-18,150.75,5,3.9
6,55.000000,125000.000000,Female,New York,2023-06-22,520.00,20,4.8
7,60.000000,250000.000000,Male,Chicago,2023-07-01,1200.00,25,5.0
8,24.000000,119666.666667,Female,Los Angeles,2023-08-11,95.00,2,3.7
9,31.000000,300000.000000,Female,Chicago,2023-09-05,210.00,6,4.1

### Problem 2: Feature Scaling
We apply `StandardScaler` to Salary and `MinMaxScaler` to Age, then display the comparisons.

In [ ]:
scaler_standard = StandardScaler()
df['Salary_Scaled'] = scaler_standard.fit_transform(df[['Salary']])

scaler_minmax = MinMaxScaler()
df['Age_Scaled'] = scaler_minmax.fit_transform(df[['Age']])

display(df[['Age', 'Age_Scaled', 'Salary', 'Salary_Scaled']].head(10))

         Age  Age_Scaled         Salary  Salary_Scaled
0  22.000000    0.000000   45000.000000  -8.994939e-01
1  25.000000    0.078947   52000.000000  -8.151664e-01
2  47.000000    0.657895  110000.000000  -1.164523e-01
3  35.000000    0.342105   75000.000000  -5.380901e-01
4  36.333333    0.377193   62000.000000  -6.946984e-01
5  28.000000    0.157895   58000.000000  -7.428856e-01
6  55.000000    0.868421  125000.000000   6.424957e-02
7  60.000000    1.000000  250000.000000   1.570099e+00
8  24.000000    0.052632  119666.666667   1.753039e-16
9  31.000000    0.236842  300000.000000   2.172438e+00

### Problem 3: Encoding Categorical Data
We transform categorical labels to numerical representations using `LabelEncoder` for Gender and `pd.get_dummies()` for City.

In [ ]:
encoder = LabelEncoder()
df['Gender_Encoded'] = encoder.fit_transform(df['Gender'])

city_dummies = pd.get_dummies(df['City'], prefix='City', dtype=int)
df = pd.concat([df, city_dummies], axis=1)

display(df.head(10))

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Scaled,Age_Scaled,Gender_Encoded,City_Chicago,City_Los Angeles,City_New York
0,22.000000,45000.000000,Male,New York,2023-01-15,120.50,1,3.5,-8.994939e-01,0.000000,1,0,0,1
1,25.000000,52000.000000,Female,Los Angeles,2023-01-16,85.00,2,4.0,-8.151664e-01,0.078947,0,0,1,0
2,47.000000,110000.000000,Female,Chicago,2023-02-20,450.25,15,4.5,-1.164523e-01,0.657895,0,1,0,0
3,35.000000,75000.000000,Male,New York,2023-03-12,300.00,8,4.2,-5.380901e-01,0.342105,1,0,0,1
4,36.333333,62000.000000,Female,Chicago,2023-04-05,50.00,4,3.8,-6.946984e-01,0.377193,0,1,0,0
5,28.000000,58000.000000,Male,Los Angeles,2023-05-18,150.75,5,3.9,-7.428856e-01,0.157895,1,0,1,0
6,55.000000,125000.000000,Female,New York,2023-06-22,520.00,20,4.8,6.424957e-02,0.868421,0,0,0,1
7,60.000000,250000.000000,Male,Chicago,2023-07-01,1200.00,25,5.0,1.570099e+00,1.000000,1,1,0,0
8,24.000000,119666.666667,Female,Los Angeles,2023-08-11,95.00,2,3.7,1.753039e-16,0.052632,0,0,1,0
9,31.000000,300000.000000,Female,Chicago,2023-09-05,210.00,6,4.1,2.172438e+00,0.236842,0,1,0,0

### Problem 4: Feature Creation
We create a new feature named `Total_Spending` and explain its usage.

In [ ]:
df['Total_Spending'] = df['Salary'] + df['Purchase_Amount']

display(df[['Salary', 'Purchase_Amount', 'Total_Spending']].head(10))

          Salary  Purchase_Amount  Total_Spending
0   45000.000000           120.50    45120.500000
1   52000.000000            85.00    52085.000000
2  110000.000000           450.25   110450.250000
3   75000.000000           300.00    75300.000000
4   62000.000000            50.00    62050.000000
5   58000.000000           150.75    58150.750000
6  125000.000000           520.00   125520.000000
7  250000.000000          1200.00   251200.000000
8  119666.666667            95.00   119761.666667
9  300000.000000           210.00   300210.000000

### Problem 5: Date Feature Extraction
We parse the Date column and extract useful subcomponents.

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.weekday

display(df[['Date', 'Year', 'Month', 'Day', 'Weekday']].head(10))

        Date  Year  Month  Day  Weekday
0 2023-01-15  2023      1   15        6
1 2023-01-16  2023      1   16        0
2 2023-02-20  2023      2   20        0
3 2023-03-12  2023      3   12        6
4 2023-04-05  2023      4    5        2
5 2023-05-18  2023      5   18        3
6 2023-06-22  2023      6   22        3
7 2023-07-01  2023      7    1        5
8 2023-08-11  2023      8   11        4
9 2023-09-05  2023      9    5        1

### Problem 6: Binning
We group the age values into distinct groups using `pd.cut()`.

In [ ]:
bins = [0, 25, 45, float('inf')]
labels = ['Young', 'Adult', 'Senior']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

display(df[['Age', 'Age_Group']].head(10))

         Age Age_Group
0  22.000000     Young
1  25.000000     Young
2  47.000000    Senior
3  35.000000     Adult
4  36.333333     Adult
5  28.000000     Adult
6  55.000000    Senior
7  60.000000    Senior
8  24.000000     Young
9  31.000000     Adult

### Problem 7: Outlier Detection
We identify salary outliers using the Interquartile Range (IQR) method.

In [ ]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower_bound) | (df['Salary'] > upper_bound)]

print(f"Lower Bound: {lower_bound}, Upper Bound: {upper_bound}")
print("Outlier Rows:")
display(outliers)

Lower Bound: -38000.0, Upper Bound: 220666.6666666667
Outlier Rows:

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Scaled,Age_Scaled,Gender_Encoded,City_Chicago,City_Los Angeles,City_New York,Total_Spending,Year,Month,Day,Weekday,Age_Group
7,60.0,250000.0,Male,Chicago,2023-07-01,1200.0,25,5.0,1.570099,1.000000,1,1,0,0,251200.0,2023,7,1,5,Senior
9,31.0,300000.0,Female,Chicago,2023-09-05,210.0,6,4.1,2.172438,0.236842,0,1,0,0,300210.0,2023,9,5,1,Adult

### Problem 8: Feature Interaction
We create a multiplicative feature combining `Experience` and `Salary`.

In [ ]:
df['Experience_Salary'] = df['Experience'] * df['Salary']

display(df[['Experience', 'Salary', 'Experience_Salary']].head(10))

   Experience         Salary  Experience_Salary
0           1   45000.000000       4.500000e+04
1           2   52000.000000       1.040000e+05
2          15  110000.000000       1.650000e+06
3           8   75000.000000       6.000000e+05
4           4   62000.000000       2.480000e+05
5           5   58000.000000       2.900000e+05
6          20  125000.000000       2.500000e+06
7          25  250000.000000       6.250000e+06
8           2  119666.666667       2.393333e+05
9           6  300000.000000       1.800000e+06

### Problem 9: Feature Selection
We calculate numeric correlation coefficients, rank them, find the weakest feature, and drop it.

In [ ]:
numeric_cols = df.select_dtypes(include=[np.number])

correlations = numeric_cols.corr()['Purchase_Amount'].sort_values(ascending=False)
print("Correlations with Purchase_Amount in descending order:")
print(correlations)

correlations_no_target = correlations.drop('Purchase_Amount')
weakest_feature = correlations_no_target.abs().idxmin()
weakest_corr_value = correlations_no_target[weakest_feature]

print(f"\nFeature to drop (lowest absolute correlation): '{weakest_feature}' (Correlation: {weakest_corr_value:.4f})")

df_final = df.drop(columns=[weakest_feature])
print("\nFinal Dataset Sample after dropping the weakest feature:")
display(df_final.head(10))

Correlations with Purchase_Amount in descending order:
Purchase_Amount      1.000000
Experience_Salary    0.970974
Experience           0.928239
Rating               0.878332
Age_Scaled           0.865960
Age                  0.865960
Total_Spending       0.558430
Salary               0.555689
Salary_Scaled        0.555689
City_Chicago         0.394057
Gender_Encoded       0.308157
Month                0.276911
Weekday              0.237250
City_New York       -0.009216
Day                 -0.286623
City_Los Angeles    -0.412049
Year                      NaN
Name: Purchase_Amount, dtype: float64

Feature to drop (lowest absolute correlation): 'City_New York' (Correlation: -0.0092)

Final Dataset Sample after dropping the weakest feature:

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Scaled,Age_Scaled,Gender_Encoded,City_Chicago,City_Los Angeles,Total_Spending,Year,Month,Day,Weekday,Age_Group,Experience_Salary
0,22.000000,45000.000000,Male,New York,2023-01-15,120.50,1,3.5,-8.994939e-01,0.000000,1,0,0,45120.500000,2023,1,15,6,Young,4.500000e+04
1,25.000000,52000.000000,Female,Los Angeles,2023-01-16,85.00,2,4.0,-8.151664e-01,0.078947,0,0,1,52085.000000,2023,1,16,0,Young,1.040000e+05
2,47.000000,110000.000000,Female,Chicago,2023-02-20,450.25,15,4.5,-1.164523e-01,0.657895,0,1,0,110450.250000,2023,2,20,0,Senior,1.650000e+06
3,35.000000,75000.000000,Male,New York,2023-03-12,300.00,8,4.2,-5.380901e-01,0.342105,1,0,0,75300.000000,2023,3,12,6,Adult,6.000000e+05
4,36.333333,62000.000000,Female,Chicago,2023-04-05,50.00,4,3.8,-6.946984e-01,0.377193,0,1,0,62050.000000,2023,4,5,2,Adult,2.480000e+05
5,28.000000,58000.000000,Male,Los Angeles,2023-05-18,150.75,5,3.9,-7.428856e-01,0.157895,1,0,1,58150.750000,2023,5,18,3,Adult,2.900000e+05
6,55.000000,125000.000000,Female,New York,2023-06-22,520.00,20,4.8,6.424957e-02,0.868421,0,0,0,125520.000000,2023,6,22,3,Senior,2.500000e+06
7,60.000000,250000.000000,Male,Chicago,2023-07-01,1200.00,25,5.0,1.570099e+00,1.000000,1,1,0,251200.000000,2023,7,1,5,Senior,6.250000e+06
8,24.000000,119666.666667,Female,Los Angeles,2023-08-11,95.00,2,3.7,1.753039e-16,0.052632,0,0,1,119761.666667,2023,8,11,4,Young,2.393333e+05
9,31.000000,300000.000000,Female,Chicago,2023-09-05,210.00,6,4.1,2.172438e+00,0.236842,0,1,0,300210.000000,2023,9,5,1,Adult,1.800000e+06